"""followers

Revision ID: 2bda148f4ce1
Revises: 25ee1454c669
Create Date: 2021-06-25 17:21:47.384265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bda148f4ce1'
down_revision = '25ee1454c669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
